<?php

namespace Database\Seeders;

use App\Models\Admin\GameList;
use Illuminate\Database\Seeder;

class JDBTablesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'code' => '14091',
                'name' => 'Piggy Bank',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14091/14091_en.png',
            ],
            [
                'code' => '14090',
                'name' => 'Wealthway',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14090/14090_en.png',
            ],
            [
                'code' => '14089',
                'name' => 'Dragon Soar',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14089/14089_en.png',
            ],
            [
                'code' => '14088',
                'name' => 'Magic Ace',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14088/14088_en.png',
            ],
            [
                'code' => '14086',
                'name' => 'Open Sesame Mega',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14086/14086_en.png',
            ],
            [
                'code' => '14087',
                'name' => 'Pop Pop Candy',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14087/14087_en.png',
            ],
            [
                'code' => '14085',
                'name' => 'Fruity Bonanza',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14085/14085_en.png',
            ],
            [
                'code' => '14042',
                'name' => 'Treasure Bowl',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14042/14042_en.png',
            ],
            [
                'code' => '14041',
                'name' => 'Mjolnir',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14041/14041_en.png',
            ],
            [
                'code' => '14077',
                'name' => 'Trump Card',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14077/14077_en.png',
            ],
            [
                'code' => '14055',
                'name' => 'Kong',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14055/14055_en.png',
            ],
            [
                'code' => '14084',
                'name' => 'CaiShen Coming',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14084/14084_en.png',
            ],
            [
                'code' => '14047',
                'name' => 'Moneybags Man',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14047/14047_en.png',
            ],
            [
                'code' => '14045',
                'name' => 'Super Niubi Deluxe',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14045/14045_en.png',
            ],
            [
                'code' => '14065',
                'name' => 'Blossom Of Wealth',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14065/14065_en.png',
            ],
            [
                'code' => '14079',
                'name' => 'Moneybags Man 2',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14079/14079_en.png',
            ],
            [
                'code' => '14036',
                'name' => 'Super Niubi',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14036/14036_en.png',
            ],
            [
                'code' => '14061',
                'name' => 'Maya Gold Crazy',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14061/14061_en.png',
            ],
            [
                'code' => '14080',
                'name' => 'Elemental Link Fire',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14080/14080_en.png',
            ],
            [
                'code' => '14030',
                'name' => 'Triple King Kong',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14030/14030_en.png',
            ],
            [
                'code' => '14083',
                'name' => 'CooCoo Farm',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14083/14083_en.png',
            ],
            [
                'code' => '14082',
                'name' => 'Elemental Link Water',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14082/14082_en.png',
            ],
            [
                'code' => '14081',
                'name' => 'Birds Party Deluxe',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14081/14081_en.png',
            ],
            [
                'code' => '14075',
                'name' => 'Fortune Neko',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14075/14075_en.png',
            ],
            [
                'code' => '14070',
                'name' => 'Book of Mystery',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14070/14070_en.png',
            ],
            [
                'code' => '14068',
                'name' => 'Prosperity Tiger',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14068/14068_en.png',
            ],
            [
                'code' => '14067',
                'name' => 'Glamorous Girl',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14067/14067_en.png',
            ],
            [
                'code' => '14064',
                'name' => 'Boom Fiesta',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14064/14064_en.png',
            ],
            [
                'code' => '14063',
                'name' => 'Big Three Dragons',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14063/14063_en.png',
            ],
            [
                'code' => '14060',
                'name' => 'Lantern Wealth',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14060/14060_en.png',
            ],
            [
                'code' => '14059',
                'name' => 'Marvelous IV',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14059/14059_en.png',
            ],
            [
                'code' => '14058',
                'name' => 'Wonder Elephant',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14058/14058_en.png',
            ],
            [
                'code' => '14054',
                'name' => 'Lucky Diamond',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14054/14054_en.png',
            ],
            [
                'code' => '14053',
                'name' => 'Spindrift 2',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14053/14053_en.png',
            ],
            [
                'code' => '14052',
                'name' => 'Jungle Jungle',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14052/14052_en.png',
            ],
            [
                'code' => '14051',
                'name' => 'Dragons Gate',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14051/14051_en.png',
            ],
            [
                'code' => '14050',
                'name' => 'Spindrift',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14050/14050_en.png',
            ],
            [
                'code' => '14048',
                'name' => 'Double Wilds',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14048/14048_en.png',
            ],
            [
                'code' => '14046',
                'name' => 'Miner Babe',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14046/14046_en.png',
            ],
            [
                'code' => '14044',
                'name' => 'Funky King Kong',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14044/14044_en.png',
            ],
            [
                'code' => '14043',
                'name' => 'Golden Disco',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14043/14043_en.png',
            ],
            [
                'code' => '14040',
                'name' => 'Pirate Treasure',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14040/14040_en.png',
            ],
            [
                'code' => '14039',
                'name' => 'Fortune Treasure',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14039/14039_en.png',
            ],
            [
                'code' => '14038',
                'name' => 'Egypt Treasure',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14038/14038_en.png',
            ],
            [
                'code' => '14035',
                'name' => 'Dragons World',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14035/14035_en.png',
            ],
            [
                'code' => '14034',
                'name' => 'Go Lai Fu',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14034/14034_en.png',
            ],
            [
                'code' => '14033',
                'name' => 'Birds Party',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14033/14033_en.png',
            ],
            [
                'code' => '14029',
                'name' => 'Orient Animals',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14029/14029_en.png',
            ],
            [
                'code' => '14027',
                'name' => 'Lucky Seven',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14027/14027_en.png',
            ],
            [
                'code' => '14025',
                'name' => 'Lucky Racing',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14025/14025_en.png',
            ],
            [
                'code' => '14022',
                'name' => 'Mining Upstart',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14022/14022_en.png',
            ],
            [
                'code' => '14021',
                'name' => 'Rolling In Money',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14021/14021_en.png',
            ],
            [
                'code' => '14018',
                'name' => 'DaJi',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14018/14018_en.png',
            ],
            [
                'code' => '14016',
                'name' => 'Kingsman',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14016/14016_en.png',
            ],
            [
                'code' => '14012',
                'name' => 'Street Fighter',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14012/14012_en.png',
            ],
            [
                'code' => '14010',
                'name' => 'Dragon',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14010/14010_en.png',
            ],
            [
                'code' => '14008',
                'name' => 'Dragon Warrior',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14008/14008_en.png',
            ],
            [
                'code' => '14007',
                'name' => 'One Punch Man',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14007/14007_en.png',
            ],
            [
                'code' => '14006',
                'name' => 'Billionaire',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14006/14006_en.png',
            ],
            [
                'code' => '14005',
                'name' => 'Mr. Bao',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14005/14005_en.png',
            ],
            [
                'code' => '14003',
                'name' => 'Panda Panda',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/14003/14003_en.png',
            ],
            [
                'code' => '15012',
                'name' => 'Legendary 5',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/15012/15012_en.png',
            ],
            [
                'code' => '15010',
                'name' => 'Chef Panda',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/15010/15010_en.png',
            ],
            [
                'code' => '15005',
                'name' => 'Lucky Fuwa',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/15005/15005_en.png',
            ],
            [
                'code' => '15002',
                'name' => 'Monkey King',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/15002/15002_en.png',
            ],
            [
                'code' => '15001',
                'name' => 'Rooster In Love',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/15001/15001_en.png',
            ],
            [
                'code' => '8020',
                'name' => 'Open Sesame',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8020/8020_en.png',
            ],
            [
                'code' => '8048',
                'name' => 'OpenSesame II',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8048/8048_en.png',
            ],
            [
                'code' => '8003',
                'name' => 'Winning Mask',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8003/8003_en.png',
            ],
            [
                'code' => '8047',
                'name' => 'Winning Mask II',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8047/8047_en.png',
            ],
            [
                'code' => '8051',
                'name' => 'Xi Yang Yang',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8051/8051_en.png',
            ],
            [
                'code' => '8050',
                'name' => 'Fortune Horse',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8050/8050_en.png',
            ],
            [
                'code' => '8049',
                'name' => 'Flirting Scholar Tang II',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8049/8049_en.png',
            ],
            [
                'code' => '8046',
                'name' => 'Guan Gong',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8046/8046_en.png',
            ],
            [
                'code' => '8044',
                'name' => 'Beauty And The Kingdom',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8044/8044_en.png',
            ],
            [
                'code' => '8035',
                'name' => 'Lucky Phoenix',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8035/8035_en.png',
            ],
            [
                'code' => '8028',
                'name' => 'Lucky Miner',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8028/8028_en.png',
            ],
            [
                'code' => '8023',
                'name' => 'Olympian Temple',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8023/8023_en.png',
            ],
            [
                'code' => '8022',
                'name' => 'MahJong',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8022/8022_en.png',
            ],
            [
                'code' => '8021',
                'name' => 'Banana Saga',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8021/8021_en.png',
            ],
            [
                'code' => '8019',
                'name' => 'Four Treasures',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8019/8019_en.png',
            ],
            [
                'code' => '8018',
                'name' => 'Napoleon',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8018/8018_en.png',
            ],
            [
                'code' => '8017',
                'name' => 'New Year',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8017/8017_en.png',
            ],
            [
                'code' => '8015',
                'name' => 'Moonlight Treasure',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8015/8015_en.png',
            ],
            [
                'code' => '8014',
                'name' => 'Lucky Lion',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8014/8014_en.png',
            ],
            [
                'code' => '8007',
                'name' => 'Lucky Qilin',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8007/8007_en.png',
            ],
            [
                'code' => '8006',
                'name' => 'Formosa Bear',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8006/8006_en.png',
            ],
            [
                'code' => '8005',
                'name' => 'Llama Adventure',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8005/8005_en.png',
            ],
            [
                'code' => '8004',
                'name' => 'Wu Kong',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8004/8004_en.png',
            ],
            [
                'code' => '8002',
                'name' => 'Flirting Scholar Tang',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8002/8002_en.png',
            ],
            [
                'code' => '8001',
                'name' => 'Lucky Dragons',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/8001/8001_en.png',
            ],
            [
                'code' => '9021',
                'name' => 'Mines2',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9021/9021_en.png',
            ],
            [
                'code' => '9020',
                'name' => 'Mole Crash',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9020/9020_en.png',
            ],
            [
                'code' => '9019',
                'name' => 'Dice',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9019/9019_en.png',
            ],
            [
                'code' => '9018',
                'name' => 'Plinko',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9018/9018_en.png',
            ],
            [
                'code' => '9017',
                'name' => 'HiLo',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9017/9017_en.png',
            ],
            [
                'code' => '9016',
                'name' => 'Goal',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9016/9016_en.png',
            ],
            [
                'code' => '9015',
                'name' => 'Firework Burst',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9015/9015_en.png',
            ],
            [
                'code' => '9014',
                'name' => 'Mines',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9014/9014_en.png',
            ],
            [
                'code' => '9012',
                'name' => 'Jogo Do Bicho',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9012/9012_en.png',
            ],
            [
                'code' => '9013',
                'name' => 'Galaxy Burst',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9013/9013_en.png',
            ],
            [
                'code' => '9011',
                'name' => 'CaiShen Party',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9011/9011_en.png',
            ],
            [
                'code' => '9010',
                'name' => 'Lucky Color Game',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9010/9010_en.png',
            ],
            [
                'code' => '9009',
                'name' => 'King Of Football',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9009/9009_en.png',
            ],
            [
                'code' => '9008',
                'name' => 'Crazy King Kong',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9008/9008_en.png',
            ],
            [
                'code' => '9007',
                'name' => 'Super Super Fruit',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9007/9007_en.png',
            ],
            [
                'code' => '9006',
                'name' => 'Huaguoshan Legends',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9006/9006_en.png',
            ],
            [
                'code' => '9004',
                'name' => 'Beer Tycoon',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9004/9004_en.png',
            ],
            [
                'code' => '9002',
                'name' => 'Happy New Year',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9002/9002_en.png',
            ],
            [
                'code' => '9001',
                'name' => 'Classic Mario',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9001/9001_en.png',
            ],
            [
                'code' => '9003',
                'name' => 'Birds And Animals',
                'game_type_id' => 1,
                'product_id' => 20,
                'image_url' => 'https://dlntdk2it99.anhuidingyue.com/jdb-assetsv3/games/9003/9003_en.png',
            ],
        ];

        // Use Laravel DB or Eloquent to insert data into the database
        foreach ($data as $gameData) {
            GameList::create($gameData);
        }
    }
}
