<?php

namespace Database\Seeders;

use App\Models\Admin\GameList;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RealTimeGamingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $games = [
            [
                'code' => '1179948',
                'name' => 'Big Santa',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/BigSanta-200x200-en.jpg',
            ],
            [
                'code' => '1180008',
                'name' => 'Sweet Shop Collect',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/SweetShopCollect-200x200-en.jpg',
            ],
            [
                'code' => '1180023',
                'name' => 'Toltec Gems',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ToltecGems-200x200-en.jpg',
            ],
            [
                'code' => '1179996',
                'name' => 'Fortunes of Olympus',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FortunesofOlympus-200x200-en.jpg',
            ],
            [
                'code' => '1179882',
                'name' => 'RTG 777',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/RTG777-200x200-en.jpg',
            ],
            [
                'code' => '1179672',
                'name' => 'Enchanted Garden',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/EnchantedGarden-200x200-en.jpg',
            ],
            [
                'code' => '1179912',
                'name' => 'Bao Ni 8',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/BaoNi8-200x200-en.jpg',
            ],
            [
                'code' => '1180000',
                'name' => 'Warrior Conquest',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/WarriorConquest-200x200-en.jpg',
            ],
            [
                'code' => '1179992',
                'name' => 'Goblins: Gluttony of Gems',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/GoblinsGluttonyofGems-200x200-en.jpg',
            ],
            [
                'code' => '1179881',
                'name' => 'Plentiful Treasure',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PlentifulTreasure-200x200-en.jpg',
            ],
            [
                'code' => '1179965',
                'name' => 'Sweet 16 Blast!',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Sweet16Blast!-200x200-en.jpg',
            ],
            [
                'code' => '1179889',
                'name' => 'Wu Zetian',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/WuZetian-200x200-en.jpg',
            ],
            [
                'code' => '1179709',
                'name' => 'Texan Tycoon',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TexanTycoon-200x200-en.jpg',
            ],
            [
                'code' => '1179830',
                'name' => 'Sweet 16',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Sweet16-200x200-en.jpg',
            ],
            [
                'code' => '1179904',
                'name' => 'Fat Cat Cafe',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FatCatCafe-200x200-en.jpg',
            ],
            [
                'code' => '1179700',
                'name' => 'T-Rex',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/T-Rex-200x200-en.jpg',
            ],
            [
                'code' => '1179847',
                'name' => 'Kung Fu Rooster',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/KungFuRooster-200x200-en.jpg',
            ],
            [
                'code' => '1179897',
                'name' => 'T-Rex II',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/T-RexII-200x200-en.jpg',
            ],
            [
                'code' => '1179803',
                'name' => 'Heavenly Treasures',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/HeavenlyTreasures-200x200-en.jpg',
            ],
            [
                'code' => '1179846',
                'name' => 'Cash Bandits 2',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/CashBandits2-200x200-en.jpg',
            ],
            [
                'code' => '1179841',
                'name' => 'Dragon Orb',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/DragonOrb-200x200-en.jpg',
            ],
            [
                'code' => '1179913',
                'name' => 'Shadow Gods',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ShadowGods-200x200-en.jpg',
            ],
            [
                'code' => '1179893',
                'name' => 'Pig Winner',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PigWinner-200x200-en.jpg',
            ],
            [
                'code' => '1179979',
                'name' => 'Shelltastic Wins!',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ShelltasticWins!-200x200-en.jpg',
            ],
            [
                'code' => '1179986',
                'name' => 'Neon Wheel 7s',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/NeonWheel7s-200x200-en.jpg',
            ],
            [
                'code' => '1179909',
                'name' => 'Emperor Panda',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/EmperorPanda-200x200-en.jpg',
            ],
            [
                'code' => '1179879',
                'name' => 'Cai Hong',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/CaiHong-200x200-en.jpg',
            ],
            [
                'code' => '1179987',
                'name' => 'Fortunate Rabbit',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FortunateRabbit-200x200-en.jpg',
            ],
            [
                'code' => '1179993',
                'name' => 'Persian Treasures',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PersianTreasures-200x200-en.jpg',
            ],
            [
                'code' => '1180009',
                'name' => 'Pharaoh Mysteries',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PharaohMysteries-200x200-en.jpg',
            ],
            [
                'code' => '1180006',
                'name' => 'Sword of the Elements',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/SwordoftheElements-200x200-en.jpg',
            ],
            [
                'code' => '1179923',
                'name' => 'Wild Hog Luau',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/WildHogLuau-200x200-en.jpg',
            ],
            [
                'code' => '1179653',
                'name' => 'Goldbeard',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Goldbeard-200x200-en.jpg',
            ],
            [
                'code' => '1180003',
                'name' => 'Fortunate Zeus',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FortunateZeus-200x200-en.jpg',
            ],
            [
                'code' => '1179710',
                'name' => 'Triple Twister',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TripleTwister-200x200-en.jpg',
            ],
            [
                'code' => '1179942',
                'name' => 'Ibiza Hotpots',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/IbizaHotpots-200x200-en.jpg',
            ],
            [
                'code' => '1179905',
                'name' => 'Ape King',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ApeKing-200x200-en.jpg',
            ],
            [
                'code' => '1179698',
                'name' => 'PayDirt!',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PayDirt!-200x200-en.jpg',
            ],
            [
                'code' => '1180020',
                'name' => 'Pyramid Pets',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PyramidPets-200x200-en.jpg',
            ],
            [
                'code' => '1179895',
                'name' => 'Trigger Happy',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TriggerHappy-200x200-en.jpg',
            ],
            [
                'code' => '1179899',
                'name' => 'Storm Lords',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/StormLords-200x200-en.jpg',
            ],
            [
                'code' => '1180018',
                'name' => 'Medieval Crusades',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/MedievalCrusades-200x200-en.jpg',
            ],
            [
                'code' => '1180010',
                'name' => 'Space Paws',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/SpacePaws-200x200-en.jpg',
            ],
            [
                'code' => '1179843',
                'name' => 'Purrfect Pets',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PurrfectPets-200x200-en.jpg',
            ],
            [
                'code' => '1179825',
                'name' => 'Nova 7s',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Nova7s-200x200-en.jpg',
            ],
            [
                'code' => '1179868',
                'name' => 'Fu Chi',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FuChi-200x200-en.jpg',
            ],
            [
                'code' => '1179819',
                'name' => 'Super 6',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Super6-200x200-en.jpg',
            ],
            [
                'code' => '1179989',
                'name' => 'Mermaid Royale',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/MermaidRoyale-200x200-en.jpg',
            ],
            [
                'code' => '1179837',
                'name' => 'Fucanglong',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Fucanglong-200x200-en.jpg',
            ],
            [
                'code' => '1179883',
                'name' => 'Fire Dragon',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FireDragon-200x200-en.jpg',
            ],
            [
                'code' => '1179887',
                'name' => 'Ancient Gods',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/AncientGods-200x200-en.jpg',
            ],
            [
                'code' => '1179826',
                'name' => 'Witch\'s Brew',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Witch\'sBrew-200x200-en.jpg',
            ],
            [
                'code' => '1179906',
                'name' => 'Lucky Rat',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/LuckyRat-200x200-en.jpg',
            ],
            [
                'code' => '1179838',
                'name' => 'Secret Symbol',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/SecretSymbol-200x200-en.jpg',
            ],
            [
                'code' => '1179885',
                'name' => 'Three Kingdom Wars',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ThreeKingdomWars-200x200-en.jpg',
            ],
            [
                'code' => '1179675',
                'name' => 'Crystal Waters',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/CrystalWaters-200x200-en.jpg',
            ],
            [
                'code' => '1179876',
                'name' => "Panda's Gold",
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => "http://prodmd.9977997.com/Image/RTG/en/Panda'sGold-200x200-en.jpg",
            ],
            [
                'code' => '1179915',
                'name' => 'Jackpot Sevens',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/JackpotSevens-200x200-en.jpg',
            ],
            [
                'code' => '1179811',
                'name' => 'Lucky 6',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Lucky6-200x200-en.jpg',
            ],
            [
                'code' => '1179874',
                'name' => 'Lucha Libre 2',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/LuchaLibre2-200x200-en.jpg',
            ],
            [
                'code' => '1179839',
                'name' => 'Popiñata',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Popiñata-200x200-en.jpg',
            ],
            [
                'code' => '1179981',
                'name' => 'Legendary Luck',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/LegendaryLuck-200x200-en.jpg',
            ],
            [
                'code' => '1179692',
                'name' => 'Coyote Cash',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/CoyoteCash-200x200-en.jpg',
            ],
            [
                'code' => '1179950',
                'name' => 'Triple Tigers',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TripleTigers-200x200-en.jpg',
            ],
            [
                'code' => '1179817',
                'name' => 'God of Wealth',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/GodofWealth-200x200-en.jpg',
            ],
            [
                'code' => '1179892',
                'name' => 'Cubee',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Cubee-200x200-en.jpg',
            ],
            [
                'code' => '1179977',
                'name' => 'Monster Spins',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/MonsterSpins-200x200-en.jpg',
            ],
            [
                'code' => '1179933',
                'name' => 'Ghana Win',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/GhanaWin-200x200-en.jpg',
            ],
            [
                'code' => '1179907',
                'name' => 'Fortune Frog',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FortuneFrog-200x200-en.jpg',
            ],
            [
                'code' => '1179790',
                'name' => 'Ghost Ship',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/GhostShip-200x200-en.jpg',
            ],
            [
                'code' => '1179770',
                'name' => 'Lucky 8',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Lucky8-200x200-en.jpg',
            ],
            [
                'code' => '1179818',
                'name' => 'The Big Bopper®',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TheBigBopper®-200x200-en.jpg',
            ],
            [
                'code' => '1179901',
                'name' => 'The Mariachi 5',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TheMariachi5-200x200-en.jpg',
            ],
            [
                'code' => '1179888',
                'name' => 'Scuba Fishing',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ScubaFishing-200x200-en.jpg',
            ],
            [
                'code' => '1179943',
                'name' => 'Buffalo Mania',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/BuffaloMania-200x200-en.jpg',
            ],
            [
                'code' => '1179890',
                'name' => 'Naughty Or Nice III',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/NaughtyOrNiceIII-200x200-en.jpg',
            ],
            [
                'code' => '1179914',
                'name' => 'Lovable Pets',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/LovablePets-200x200-en.jpg',
            ],
            [
                'code' => '1179820',
                'name' => 'Zhanshi',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Zhanshi-200x200-en.jpg',
            ],
            [
                'code' => '1179947',
                'name' => 'Thai Emerald',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ThaiEmerald-200x200-en.jpg',
            ],
            [
                'code' => '1179871',
                'name' => 'Fantasy Mission Force',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FantasyMissionForce-200x200-en.jpg',
            ],
            [
                'code' => '1179821',
                'name' => 'Enchanted Garden II',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/EnchantedGardenII-200x200-en.jpg',
            ],
            [
                'code' => '1179813',
                'name' => 'Bubble Bubble',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/BubbleBubble-200x200-en.jpg',
            ],
            [
                'code' => '1179727',
                'name' => 'Count Spectacular',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/CountSpectacular-200x200-en.jpg',
            ],
            [
                'code' => '1179880',
                'name' => 'I, Zombie',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/I,Zombie-200x200-en.jpg',
            ],
            [
                'code' => '1179674',
                'name' => "Aladdin's Wishes",
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => "http://prodmd.9977997.com/Image/RTG/en/Aladdin'sWishes-200x200-en.jpg",
            ],
            [
                'code' => '1179848',
                'name' => 'Bubble Bubble 2',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/BubbleBubble2-200x200-en.jpg',
            ],
            [
                'code' => '1179823',
                'name' => 'Samba Sunset',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/SambaSunset-200x200-en.jpg',
            ],
            [
                'code' => '1179994',
                'name' => 'Buccaneer Bash',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/BuccaneerBash-200x200-en.jpg',
            ],
            [
                'code' => '1179930',
                'name' => 'Ox Bonanza',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/OxBonanza-200x200-en.jpg',
            ],
            [
                'code' => '1179925',
                'name' => 'Rave Riches',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/RaveRiches-200x200-en.jpg',
            ],
            [
                'code' => '1179822',
                'name' => 'Panda Magic',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PandaMagic-200x200-en.jpg',
            ],
            [
                'code' => '1179952',
                'name' => 'Chunky Monkey',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ChunkyMonkey-200x200-en.jpg',
            ],
            [
                'code' => '1179898',
                'name' => 'Football Fortunes',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FootballFortunes-200x200-en.jpg',
            ],
            [
                'code' => '1179916',
                'name' => 'CAI BLING',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/CAIBLING-200x200-en.jpg',
            ],
            [
                'code' => '1179872',
                'name' => 'Eagle Shadow Fist',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/EagleShadowFist-200x200-en.jpg',
            ],
            [
                'code' => '1179873',
                'name' => 'Ritchie Valens™ La Bamba',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/RitchieValens™LaBamba-200x200-en.jpg',
            ],
            [
                'code' => '1179779',
                'name' => 'Ninja Star',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/NinjaStar-200x200-en.jpg',
            ],
            [
                'code' => '1179870',
                'name' => 'Shanghai Lights',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ShanghaiLights-200x200-en.jpg',
            ],
            [
                'code' => '1179804',
                'name' => 'Voodoo Magic',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/VoodooMagic-200x200-en.jpg',
            ],
            [
                'code' => '1179894',
                'name' => "Mermaid's Pearls",
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => "http://prodmd.9977997.com/Image/RTG/en/Mermaid'sPearls-200x200-en.jpg",
            ],
            [
                'code' => '1179884',
                'name' => 'Stardust',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Stardust-200x200-en.jpg',
            ],
            [
                'code' => '1179816',
                'name' => 'Eternal Love',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/EternalLove-200x200-en.jpg',
            ],
            [
                'code' => '1179953',
                'name' => 'Monarch Mayhem',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/MonarchMayhem-200x200-en.jpg',
            ],
            [
                'code' => '1179924',
                'name' => 'Dancing Wins',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/DancingWins-200x200-en.jpg',
            ],
            [
                'code' => '1179869',
                'name' => 'Swindle All The Way',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/SwindleAllTheWay-200x200-en.jpg',
            ],
            [
                'code' => '1179773',
                'name' => 'Loch Ness Loot',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/LochNessLoot-200x200-en.jpg',
            ],
            [
                'code' => '1179861',
                'name' => 'Santastic!',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Santastic!-200x200-en.jpg',
            ],
            [
                'code' => '1179693',
                'name' => "Rudolph's Revenge",
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => "http://prodmd.9977997.com/Image/RTG/en/Rudolph'sRevenge-200x200-en.jpg",
            ],
            [
                'code' => '1179798',
                'name' => 'High Fashion',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/HighFashion-200x200-en.jpg',
            ],
            [
                'code' => '1179714',
                'name' => 'Naughty Or Nice?',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/NaughtyOrNice-200x200-en.jpg',
            ],
            [
                'code' => '1179836',
                'name' => 'Megaquarium',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Megaquarium-200x200-en.jpg',
            ],
            [
                'code' => '1179807',
                'name' => 'The Three Stooges® Brideless Groom',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TheThreeStooges®BridelessGroom-200x200-en.jpg',
            ],
            [
                'code' => '1179796',
                'name' => 'Regal Riches',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/RegalRiches-200x200-en.jpg',
            ],
            [
                'code' => '1179664',
                'name' => 'Hillbillies',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Hillbillies-200x200-en.jpg',
            ],
            [
                'code' => '1179685',
                'name' => 'Penguin Power',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PenguinPower-200x200-en.jpg',
            ],
            [
                'code' => '1179771',
                'name' => 'Builder Beaver',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/BuilderBeaver-200x200-en.jpg',
            ],
            [
                'code' => '1179797',
                'name' => 'Small Fortune',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/SmallFortune-200x200-en.jpg',
            ],
            [
                'code' => '1179877',
                'name' => 'Secret Jungle',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/SecretJungle-200x200-en.jpg',
            ],
            [
                'code' => '1179814',
                'name' => 'The Nice List',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TheNiceList-200x200-en.jpg',
            ],
            [
                'code' => '1179858',
                'name' => 'The Three Stooges® II',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TheThreeStooges®II-200x200-en.jpg',
            ],
            [
                'code' => '1179663',
                'name' => 'Mermaid Queen',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/MermaidQueen-200x200-en.jpg',
            ],
            [
                'code' => '1179802',
                'name' => 'Football Frenzy',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FootballFrenzy-200x200-en.jpg',
            ],
            [
                'code' => '1179795',
                'name' => 'Ocean Oddities',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/OceanOddities-200x200-en.jpg',
            ],
            [
                'code' => '1179828',
                'name' => 'Snowmania',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Snowmania-200x200-en.jpg',
            ],
            [
                'code' => '1179805',
                'name' => 'The Naughty List',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TheNaughtyList-200x200-en.jpg',
            ],
        ];

        foreach ($games as $gameData) {
            GameList::create($gameData);
        }

    }
}
