<?php

namespace Database\Seeders;

use App\Models\Admin\GameList;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class YggdrasilSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $games = [
            [
                'code' => '880029',
                'name' => 'Jokerizer',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880029.jpg',
            ],
            [
                'code' => '880031',
                'name' => 'Fruitoids',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880031.jpg',
            ],
            [
                'code' => '880033',
                'name' => 'Dark Joker Rizes',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880033.jpg',
            ],
            [
                'code' => '880034',
                'name' => 'Chibeasties',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880034.jpg',
            ],
            [
                'code' => '880037',
                'name' => 'Nirvana',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880037.jpg',
            ],
            [
                'code' => '880038',
                'name' => 'Incinerator',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880038.jpg',
            ],
            [
                'code' => '880041',
                'name' => 'Seasons',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880041.jpg',
            ],
            [
                'code' => '880042',
                'name' => 'Legend of the Golden Monkey',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880042.jpg',
            ],
            [
                'code' => '880043',
                'name' => 'Bicicleta',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880043.jpg',
            ],
            [
                'code' => '880044',
                'name' => 'Big Blox',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880044.jpg',
            ],
            [
                'code' => '880045',
                'name' => 'Double Dragons',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880045.jpg',
            ],
            [
                'code' => '880047',
                'name' => 'Alchymedes',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880047.jpg',
            ],
            [
                'code' => '880048',
                'name' => 'Beauty and the Beast',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880048.jpg',
            ],
            [
                'code' => '880050',
                'name' => 'Jungle Books',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880050.jpg',
            ],
            [
                'code' => '880059',
                'name' => 'Lucha Maniacs',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880059.jpg',
            ],
            [
                'code' => '880060',
                'name' => 'TutsTwister',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880060.jpg',
            ],
            [
                'code' => '880061',
                'name' => 'Penguin City',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880061.jpg',
            ],
            [
                'code' => '880063',
                'name' => 'Wolf Hunters',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880063.jpg',
            ],
            [
                'code' => '880064',
                'name' => 'Dark Vortex',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880064.jpg',
            ],
            [
                'code' => '880065',
                'name' => 'Baron Samedi',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880065.jpg',
            ],
            [
                'code' => '880066',
                'name' => 'Time Travel Tigers',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880066.jpg',
            ],
            [
                'code' => '880072',
                'name' => 'Wilhelm Tell',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880072.jpg',
            ],
            [
                'code' => '880074',
                'name' => 'Age of Asgard',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880074.jpg',
            ],
            [
                'code' => '880075',
                'name' => 'Wild Robo Factory',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880075.jpg',
            ],
            [
                'code' => '880076',
                'name' => 'Yokozuna Clash',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880076.jpg',
            ],
            [
                'code' => '880078',
                'name' => "Aldo's Journey",
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880078.jpg',
            ],
            [
                'code' => '880080',
                'name' => 'Temple Stacks: Splitz',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880080.jpg',
            ],
            [
                'code' => '880081',
                'name' => 'Brazil Bomba',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880081.jpg',
            ],
            [
                'code' => '880083',
                'name' => 'Neon Rush: Splitz',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880083.jpg',
            ],
            [
                'code' => '880087',
                'name' => 'Football Glory',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880087.jpg',
            ],
            [
                'code' => '880088',
                'name' => 'Vault of Fortune',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880088.jpg',
            ],
            [
                'code' => '880089',
                'name' => 'Lightning Joker',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880089.jpg',
            ],
            [
                'code' => '880095',
                'name' => 'Easter Island 2',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880095.jpg',
            ],
            [
                'code' => '880098',
                'name' => 'Vikings go to Valhalla',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880098.jpg',
            ],
            [
                'code' => '880099',
                'name' => 'Gator Gold Gigablox',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880099.jpg',
            ],
            [
                'code' => '880101',
                'name' => 'Suncatcher Gigablox',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880101.jpg',
            ],
            [
                'code' => '880102',
                'name' => 'Raptor Doublemax',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880102.jpg',
            ],
            [
                'code' => '880103',
                'name' => 'Golden Fish Tank 2 Gigablox',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880103.jpg',
            ],
            [
                'code' => '880104',
                'name' => 'Orient Express',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880104.jpg',
            ],
            [
                'code' => '880105',
                'name' => 'Trolls Bridge',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880105.jpg',
            ],
            [
                'code' => '880106',
                'name' => 'Royal Family',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880106.jpg',
            ],
            [
                'code' => '880107',
                'name' => 'Pirates: Smugglers Paradise',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880107.jpg',
            ],
            [
                'code' => '880109',
                'name' => 'Avatars: Gateway Guardians',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880109.jpg',
            ],
            [
                'code' => '880110',
                'name' => 'Pirates 2: Mutiny',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880110.jpg',
            ],
            [
                'code' => '880115',
                'name' => 'Golden Gorgon',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880115.jpg',
            ],
            [
                'code' => '880120',
                'name' => 'Pushy Cats',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880120.jpg',
            ],
            [
                'code' => '880129',
                'name' => '90k Yeti Gigablox',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880129.jpg',
            ],
            [
                'code' => '880130',
                'name' => 'Spina Colada',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880130.jpg',
            ],
            [
                'code' => '880135',
                'name' => 'Easter Island',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880135.jpg',
            ],
            [
                'code' => '880136',
                'name' => 'Rainbow Ryan',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880136.jpg',
            ],
            [
                'code' => '880138',
                'name' => '10x Rewind',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880138.jpg',
            ],
            [
                'code' => '880140',
                'name' => 'TIGER_TIGER',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880140.jpg',
            ],
            [
                'code' => '880141',
                'name' => 'Medusa Hot 1',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880141.jpg',
            ],
            [
                'code' => '880142',
                'name' => 'Hammer of Gods',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880142.jpg',
            ],
            [
                'code' => '880143',
                'name' => 'Valley of the Gods',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880143.jpg',
            ],
            [
                'code' => '880146',
                'name' => 'Vikings Go To Hell',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880146.jpg',
            ],
            [
                'code' => '880148',
                'name' => 'Winterberries',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880148.jpg',
            ],
            [
                'code' => '880149',
                'name' => 'Valkyries',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880149.jpg',
            ],
            [
                'code' => '880150',
                'name' => 'Valley of the Gods 2',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880150.jpg',
            ],
            [
                'code' => '880151',
                'name' => 'Multifly!',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880151.jpg',
            ],
            [
                'code' => '880153',
                'name' => 'Lucky Neko',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880153.jpg',
            ],
            [
                'code' => '880154',
                'name' => 'Hades',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880154.jpg',
            ],
            [
                'code' => '880155',
                'name' => 'Carol of The Elves',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880155.jpg',
            ],
            [
                'code' => '880156',
                'name' => 'Sunny Shores',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880156.jpg',
            ],
            [
                'code' => '880157',
                'name' => 'Dwarf Mine',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880157.jpg',
            ],
            [
                'code' => '880158',
                'name' => 'Gem Rocks',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880158.jpg',
            ],
            [
                'code' => '880159',
                'name' => 'Pumpkin Smash',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880159.jpg',
            ],
            [
                'code' => '880160',
                'name' => "Hanzo's Dojo",
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880160.jpg',
            ],
            [
                'code' => '880161',
                'name' => 'SavannaRoar',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880161.jpg',
            ],
            [
                'code' => '880162',
                'name' => 'Reel Desire',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880162.jpg',
            ],
            [
                'code' => '880164',
                'name' => 'Cazino Cosmos',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880164.jpg',
            ],
            [
                'code' => '880165',
                'name' => 'The One Armed Bandit',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880165.jpg',
            ],
            [
                'code' => '880166',
                'name' => 'Hyperburst',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880166.jpg',
            ],
            [
                'code' => '880167',
                'name' => 'Vikings go Berzerk',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880167.jpg',
            ],
            [
                'code' => '880168',
                'name' => 'Vikings go Wild',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880168.jpg',
            ],
            [
                'code' => '880169',
                'name' => 'Sahara Nights',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880169.jpg',
            ],
            [
                'code' => '880170',
                'name' => 'Champions of Rome',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880170.jpg',
            ],
            [
                'code' => '880171',
                'name' => 'Syncronite',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880171.jpg',
            ],
            [
                'code' => '880172',
                'name' => "Arthur's Fortune",
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880172.jpg',
            ],
            [
                'code' => '880173',
                'name' => 'Blood Moon Wilds',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880173.jpg',
            ],
            [
                'code' => '880174',
                'name' => 'Cazino Zeppelin',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880174.jpg',
            ],
            [
                'code' => '880175',
                'name' => 'Golden Fish Tank',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880175.jpg',
            ],
            [
                'code' => '880176',
                'name' => 'Gator Gold Deluxe Gigablox',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880176.jpg',
            ],
            [
                'code' => '880178',
                'name' => 'Hunters Moon',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880178.jpg',
            ],
            [
                'code' => '880179',
                'name' => 'Vikings Go Berzerk: Reloaded',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880179.jpg',
            ],
            [
                'code' => '880180',
                'name' => 'SERENDIPITY',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880180.jpg',
            ],
            [
                'code' => '880181',
                'name' => 'Cthulhu',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880181.jpg',
            ],
            [
                'code' => '880183',
                'name' => 'Monster Blox',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880183.jpg',
            ],
            [
                'code' => '880185',
                'name' => 'Cazino Zeppelin Reloaded',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880185.jpg',
            ],
            [
                'code' => '880187',
                'name' => 'ThunderOfThor',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880187.jpg',
            ],
            [
                'code' => '880188',
                'name' => 'Jumbo Jellies',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880188.jpg',
            ],
            [
                'code' => '880211',
                'name' => "Boilin' Pots",
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880211.jpg',
            ],
            [
                'code' => '880213',
                'name' => 'MexoMax! Multimax',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880213.jpg',
            ],
            [
                'code' => '880217',
                'name' => 'Of Sabers and Monsters Wild Fight',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880217.jpg',
            ],
            [
                'code' => '880220',
                'name' => 'Golden Chip Roulette',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880220.jpg',
            ],
            [
                'code' => '880224',
                'name' => 'Calavera Crush',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880224.jpg',
            ],
            [
                'code' => '880225',
                'name' => 'Florageddon!',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880225.jpg',
            ],
            [
                'code' => '880228',
                'name' => 'Champion of the Underworld Gigablox Wild Fight',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880228.jpg',
            ],
            [
                'code' => '880234',
                'name' => 'Firekick! Multimax',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880234.jpg',
            ],
            [
                'code' => '880237',
                'name' => 'Christmas Plaza DoubleMax',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880237.jpg',
            ],
            [
                'code' => '880244',
                'name' => 'Neon Villains Doublemax',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880244.jpg',
            ],
            [
                'code' => '880248',
                'name' => 'Winterberries 2',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880248.jpg',
            ],
            [
                'code' => '880255',
                'name' => 'E-Force',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880255.jpg',
            ],
            [
                'code' => '880257',
                'name' => 'Giganimals Gigablox',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880257.jpg',
            ],
            [
                'code' => '880260',
                'name' => 'Devour the Weak',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880260.jpg',
            ],
            [
                'code' => '880262',
                'name' => 'Nice Catch Doublemax',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880262.jpg',
            ],
            [
                'code' => '880267',
                'name' => 'Ragnawolves',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880267.jpg',
            ],
            [
                'code' => '880269',
                'name' => 'Candyfinity',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880269.jpg',
            ],
            [
                'code' => '880273',
                'name' => 'Starfire Fortunes Tophit',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880273.jpg',
            ],
            [
                'code' => '880275',
                'name' => 'Badger Miners',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880275.jpg',
            ],
            [
                'code' => '880278',
                'name' => 'Notre-Dame Tales',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880278.jpg',
            ],
            [
                'code' => '880280',
                'name' => 'Shaker Club',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880280.jpg',
            ],
            [
                'code' => '880284',
                'name' => 'Enchanted Water',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880284.jpg',
            ],
            [
                'code' => '880286',
                'name' => 'Gigagong Gigablox',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880286.jpg',
            ],
            [
                'code' => '880290',
                'name' => "Fatz's Diner",
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880290.jpg',
            ],
            [
                'code' => '880292',
                'name' => 'Vampire Riches',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880292.jpg',
            ],
            [
                'code' => '880295',
                'name' => 'Wild Stack Frenzy',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880295.jpg',
            ],
            [
                'code' => '880296',
                'name' => 'Defenders of Mystica',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880296.jpg',
            ],
            [
                'code' => '880302',
                'name' => 'Rock Star Santa',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880302.jpg',
            ],
            [
                'code' => '880308',
                'name' => 'Nice Catch 2',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880308.jpg',
            ],
            [
                'code' => '880310',
                'name' => 'Ragnaravens',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880310.jpg',
            ],
            [
                'code' => '880316',
                'name' => 'Rainbow Ryan 2',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880316.jpg',
            ],
            [
                'code' => '880329',
                'name' => 'Trolls Bridge 2',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880329.jpg',
            ],
            [
                'code' => '880330',
                'name' => 'Racing Lovers',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880330.jpg',
            ],
            [
                'code' => '880332',
                'name' => 'Wild Mantra',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880332.jpg',
            ],
            [
                'code' => '880352',
                'name' => 'Monkeys Go Bananas',
                'game_type_id' => 1,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880352.jpg',
            ],
            [
                'code' => '880029',
                'name' => 'Jokerizer',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880029.jpg',
            ],
            [
                'code' => '880031',
                'name' => 'Fruitoids',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880031.jpg',
            ],
            [
                'code' => '880033',
                'name' => 'Dark Joker Rizes',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880033.jpg',
            ],
            [
                'code' => '880034',
                'name' => 'Chibeasties',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880034.jpg',
            ],
            [
                'code' => '880037',
                'name' => 'Nirvana',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880037.jpg',
            ],
            [
                'code' => '880038',
                'name' => 'Incinerator',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880038.jpg',
            ],
            [
                'code' => '880041',
                'name' => 'Seasons',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880041.jpg',
            ],
            [
                'code' => '880042',
                'name' => 'Legend of the Golden Monkey',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880042.jpg',
            ],
            [
                'code' => '880043',
                'name' => 'Bicicleta',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880043.jpg',
            ],
            [
                'code' => '880044',
                'name' => 'Big Blox',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880044.jpg',
            ],
            [
                'code' => '880045',
                'name' => 'Double Dragons',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880045.jpg',
            ],
            [
                'code' => '880047',
                'name' => 'Alchymedes',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880047.jpg',
            ],
            [
                'code' => '880048',
                'name' => 'Beauty and the Beast',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880048.jpg',
            ],
            [
                'code' => '880050',
                'name' => 'Jungle Books',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880050.jpg',
            ],
            [
                'code' => '880059',
                'name' => 'Lucha Maniacs',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880059.jpg',
            ],
            [
                'code' => '880060',
                'name' => 'TutsTwister',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880060.jpg',
            ],
            [
                'code' => '880061',
                'name' => 'Penguin City',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880061.jpg',
            ],
            [
                'code' => '880063',
                'name' => 'Wolf Hunters',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880063.jpg',
            ],
            [
                'code' => '880064',
                'name' => 'Dark Vortex',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880064.jpg',
            ],
            [
                'code' => '880065',
                'name' => 'Baron Samedi',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880065.jpg',
            ],
            [
                'code' => '880066',
                'name' => 'Time Travel Tigers',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880066.jpg',
            ],
            [
                'code' => '880072',
                'name' => 'Wilhelm Tell',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880072.jpg',
            ],
            [
                'code' => '880029',
                'name' => 'Jokerizer',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880029.jpg',
            ],
            [
                'code' => '880031',
                'name' => 'Fruitoids',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880031.jpg',
            ],
            [
                'code' => '880033',
                'name' => 'Dark Joker Rizes',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880033.jpg',
            ],
            [
                'code' => '880034',
                'name' => 'Chibeasties',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880034.jpg',
            ],
            [
                'code' => '880037',
                'name' => 'Nirvana',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880037.jpg',
            ],
            [
                'code' => '880038',
                'name' => 'Incinerator',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880038.jpg',
            ],
            [
                'code' => '880041',
                'name' => 'Seasons',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880041.jpg',
            ],
            [
                'code' => '880042',
                'name' => 'Legend of the Golden Monkey',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880042.jpg',
            ],
            [
                'code' => '880043',
                'name' => 'Bicicleta',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880043.jpg',
            ],
            [
                'code' => '880044',
                'name' => 'Big Blox',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880044.jpg',
            ],
            [
                'code' => '880045',
                'name' => 'Double Dragons',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880045.jpg',
            ],
            [
                'code' => '880047',
                'name' => 'Alchymedes',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880047.jpg',
            ],
            [
                'code' => '880048',
                'name' => 'Beauty and the Beast',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880048.jpg',
            ],
            [
                'code' => '880050',
                'name' => 'Jungle Books',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880050.jpg',
            ],
            [
                'code' => '880059',
                'name' => 'Lucha Maniacs',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880059.jpg',
            ],
            [
                'code' => '880060',
                'name' => 'TutsTwister',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880060.jpg',
            ],
            [
                'code' => '880061',
                'name' => 'Penguin City',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880061.jpg',
            ],
            [
                'code' => '880063',
                'name' => 'Wolf Hunters',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880063.jpg',
            ],
            [
                'code' => '880064',
                'name' => 'Dark Vortex',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880064.jpg',
            ],
            [
                'code' => '880065',
                'name' => 'Baron Samedi',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880065.jpg',
            ],
            [
                'code' => '880066',
                'name' => 'Time Travel Tigers',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880066.jpg',
            ],
            [
                'code' => '880072',
                'name' => 'Wilhelm Tell',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880072.jpg',
            ],
            [
                'code' => '880074',
                'name' => 'Age of Asgard',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880074.jpg',
            ],
            [
                'code' => '880075',
                'name' => 'Wild Robo Factory',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880075.jpg',
            ],
            [
                'code' => '880076',
                'name' => 'Yokozuna Clash',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880076.jpg',
            ],
            [
                'code' => '880078',
                'name' => 'Aldo\'s Journey',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880078.jpg',
            ],
            [
                'code' => '880080',
                'name' => 'Temple Stacks: Splitz',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880080.jpg',
            ],
            [
                'code' => '880081',
                'name' => 'Brazil Bomba',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880081.jpg',
            ],
            [
                'code' => '880083',
                'name' => 'Neon Rush: Splitz',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880083.jpg',
            ],
            [
                'code' => '880087',
                'name' => 'Football Glory',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880087.jpg',
            ],
            [
                'code' => '880088',
                'name' => 'Vault of Fortune',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880088.jpg',
            ],
            [
                'code' => '880089',
                'name' => 'Lightning Joker',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880089.jpg',
            ],
            [
                'code' => '880095',
                'name' => 'Easter Island 2',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880095.jpg',
            ],
            [
                'code' => '880098',
                'name' => 'Vikings go to Valhalla',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880098.jpg',
            ],
            [
                'code' => '880099',
                'name' => 'Gator Gold Gigablox',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880099.jpg',
            ],
            [
                'code' => '880101',
                'name' => 'Suncatcher Gigablox',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880101.jpg',
            ],
            [
                'code' => '880102',
                'name' => 'Raptor Doublemax',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880102.jpg',
            ],
            [
                'code' => '880103',
                'name' => 'Golden Fish Tank 2 Gigablox',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880103.jpg',
            ],
            [
                'code' => '880104',
                'name' => 'Orient Express',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880104.jpg',
            ],
            [
                'code' => '880105',
                'name' => 'Trolls Bridge',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880105.jpg',
            ],
            [
                'code' => '880106',
                'name' => 'Royal Family',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880106.jpg',
            ],
            [
                'code' => '880107',
                'name' => 'Pirates: Smugglers Paradise',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880107.jpg',
            ],
            [
                'code' => '880109',
                'name' => 'Avatars: Gateway Guardians',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880109.jpg',
            ],
            [
                'code' => '880110',
                'name' => 'Pirates 2: Mutiny',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880110.jpg',
            ],
            [
                'code' => '880115',
                'name' => 'Golden Gorgon',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880115.jpg',
            ],
            [
                'code' => '880120',
                'name' => 'Pushy Cats',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880120.jpg',
            ],
            [
                'code' => '880129',
                'name' => '90k Yeti Gigablox',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880129.jpg',
            ],
            [
                'code' => '880130',
                'name' => 'Spina Colada',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880130.jpg',
            ],
            [
                'code' => '880135',
                'name' => 'Easter Island',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880135.jpg',
            ],
            [
                'code' => '880136',
                'name' => 'Rainbow Ryan',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880136.jpg',
            ],
            [
                'code' => '880138',
                'name' => '10x Rewind',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880138.jpg',
            ],
            [
                'code' => '880140',
                'name' => 'TIGER_TIGER',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880140.jpg',
            ],
            [
                'code' => '880141',
                'name' => 'Medusa Hot 1',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880141.jpg',
            ],
            [
                'code' => '880142',
                'name' => 'Hammer of Gods',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880142.jpg',
            ],
            [
                'code' => '880143',
                'name' => 'Valley of the Gods',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880143.jpg',
            ],
            [
                'code' => '880146',
                'name' => 'Vikings Go To Hell',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880146.jpg',
            ],
            [
                'code' => '880148',
                'name' => 'Winterberries',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880148.jpg',
            ],
            [
                'code' => '880149',
                'name' => 'Valkyries',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880149.jpg',
            ],
            [
                'code' => '880150',
                'name' => 'Valley of the Gods 2',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880150.jpg',
            ],
            [
                'code' => '880151',
                'name' => 'Multifly!',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880151.jpg',
            ],
            [
                'code' => '880153',
                'name' => 'Lucky Neko',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880153.jpg',
            ],
            [
                'code' => '880154',
                'name' => 'Hades',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880154.jpg',
            ],
            [
                'code' => '880155',
                'name' => 'Carol of The Elves',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880155.jpg',
            ],
            [
                'code' => '880156',
                'name' => 'Sunny Shores',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880156.jpg',
            ],
            [
                'code' => '880157',
                'name' => 'Dwarf Mine',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880157.jpg',
            ],
            [
                'code' => '880158',
                'name' => 'Gem Rocks',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880158.jpg',
            ],
            [
                'code' => '880159',
                'name' => 'Pumpkin Smash',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880159.jpg',
            ],
            [
                'code' => '880160',
                'name' => 'Hanzo\'s Dojo',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880160.jpg',
            ],
            [
                'code' => '880161',
                'name' => 'SavannaRoar',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880161.jpg',
            ],
            [
                'code' => '880162',
                'name' => 'Reel Desire',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880162.jpg',
            ],
            [
                'code' => '880164',
                'name' => 'Cazino Cosmos',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880164.jpg',
            ],
            [
                'code' => '880165',
                'name' => 'The One Armed Bandit',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880165.jpg',
            ],
            [
                'code' => '880166',
                'name' => 'Hyperburst',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880166.jpg',
            ],
            [
                'code' => '880167',
                'name' => 'Vikings go Berzerk',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880167.jpg',
            ],
            [
                'code' => '880168',
                'name' => 'Vikings go Wild',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880168.jpg',
            ],
            [
                'code' => '880169',
                'name' => 'Sahara Nights',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880169.jpg',
            ],
            [
                'code' => '880170',
                'name' => 'Champions of Rome',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880170.jpg',
            ],
            [
                'code' => '880171',
                'name' => 'Syncronite',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880171.jpg',
            ],
            [
                'code' => '880172',
                'name' => 'Arthur\'s Fortune',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880172.jpg',
            ],
            [
                'code' => '880173',
                'name' => 'Blood Moon Wilds',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880173.jpg',
            ],
            [
                'code' => '880174',
                'name' => 'Cazino Zeppelin',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880174.jpg',
            ],
            [
                'code' => '880175',
                'name' => 'Golden Fish Tank',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880175.jpg',
            ],
            [
                'code' => '880176',
                'name' => 'Gator Gold Deluxe Gigablox',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880176.jpg',
            ],
            [
                'code' => '880178',
                'name' => 'Hunters Moon',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880178.jpg',
            ],
            [
                'code' => '880179',
                'name' => 'Vikings Go Berzerk: Reloaded',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880179.jpg',
            ],
            [
                'code' => '880180',
                'name' => 'SERENDIPITY',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880180.jpg',
            ],
            [
                'code' => '880181',
                'name' => 'Cthulhu',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880181.jpg',
            ],
            [
                'code' => '880183',
                'name' => 'Monster Blox',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880183.jpg',
            ],
            [
                'code' => '880185',
                'name' => 'Cazino Zeppelin Reloaded',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880185.jpg',
            ],
            [
                'code' => '880187',
                'name' => 'ThunderOfThor',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880187.jpg',
            ],
            [
                'code' => '880188',
                'name' => 'Jumbo Jellies',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880188.jpg',
            ],
            [
                'code' => '880211',
                'name' => 'Boilin\' Pots',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880211.jpg',
            ],
            [
                'code' => '880213',
                'name' => 'MexoMax! Multimax',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880213.jpg',
            ],
            [
                'code' => '880217',
                'name' => 'Of Sabers and Monsters Wild Fight',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880217.jpg',
            ],
            [
                'code' => '880220',
                'name' => 'Golden Chip Roulette',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880220.jpg',
            ],
            [
                'code' => '880224',
                'name' => 'Calavera Crush',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880224.jpg',
            ],
            [
                'code' => '880225',
                'name' => 'Florageddon!',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880225.jpg',
            ],
            [
                'code' => '880228',
                'name' => 'Champion of the Underworld Gigablox Wild Fight',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880228.jpg',
            ],
            [
                'code' => '880234',
                'name' => 'Firekick! Multimax',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880234.jpg',
            ],
            [
                'code' => '880237',
                'name' => 'Christmas Plaza DoubleMax',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880237.jpg',
            ],
            [
                'code' => '880244',
                'name' => 'Neon Villains Doublemax',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880244.jpg',
            ],
            [
                'code' => '880248',
                'name' => 'Winterberries 2',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880248.jpg',
            ],
            [
                'code' => '880255',
                'name' => 'E-Force',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880255.jpg',
            ],
            [
                'code' => '880257',
                'name' => 'Giganimals Gigablox',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880257.jpg',
            ],
            [
                'code' => '880260',
                'name' => 'Devour the Weak',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880260.jpg',
            ],
            [
                'code' => '880262',
                'name' => 'Nice Catch Doublemax',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880262.jpg',
            ],
            [
                'code' => '880267',
                'name' => 'Ragnawolves',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880267.jpg',
            ],
            [
                'code' => '880269',
                'name' => 'Candyfinity',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880269.jpg',
            ],
            [
                'code' => '880273',
                'name' => 'Starfire Fortunes Tophit',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880273.jpg',
            ],
            [
                'code' => '880275',
                'name' => 'Badger Miners',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880275.jpg',
            ],
            [
                'code' => '880278',
                'name' => 'Notre-Dame Tales',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880278.jpg',
            ],
            [
                'code' => '880280',
                'name' => 'Shaker Club',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880280.jpg',
            ],
            [
                'code' => '880284',
                'name' => 'Enchanted Water',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880284.jpg',
            ],
            [
                'code' => '880286',
                'name' => 'Gigagong Gigablox',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880286.jpg',
            ],
            [
                'code' => '880290',
                'name' => 'Fatz\'s Diner',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880290.jpg',
            ],
            [
                'code' => '880292',
                'name' => 'Vampire Riches',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880292.jpg',
            ],
            [
                'code' => '880295',
                'name' => 'Wild Stack Frenzy',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880295.jpg',
            ],
            [
                'code' => '880296',
                'name' => 'Defenders of Mystica',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880296.jpg',
            ],
            [
                'code' => '880302',
                'name' => 'Rock Star Santa',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880302.jpg',
            ],
            [
                'code' => '880308',
                'name' => 'Nice Catch 2',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880308.jpg',
            ],
            [
                'code' => '880310',
                'name' => 'Ragnaravens',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880310.jpg',
            ],
            [
                'code' => '880316',
                'name' => 'Rainbow Ryan 2',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880316.jpg',
            ],
            [
                'code' => '880329',
                'name' => 'Trolls Bridge 2',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880329.jpg',
            ],
            [
                'code' => '880330',
                'name' => 'Racing Lovers',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880330.jpg',
            ],
            [
                'code' => '880332',
                'name' => 'Wild Mantra',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880332.jpg',
            ],
            [
                'code' => '880352',
                'name' => 'Monkeys Go Bananas',
                'game_type_id' => 2,
                'product_id' => 6,
                'image_url' => 'http://prodmd.9977997.com/Image/AT/en/880352.jpg',
            ],
        ];

        foreach ($games as $gameData) {
            GameList::create($gameData);
        }

    }
}
